#!/usr/bin/env python3
"""Generate the starter .cube LUTs shipped with PhotoStyler.

These are placeholders with real colour science behind them, not final looks.
Murali's exported Lightroom LUTs drop into PhotoStyler/Resources/LUTs/ and
replace them without any code change (task 4.7).

Usage:  python3 tools/generate_luts.py
"""

import os

SIZE = 33
OUT = os.path.join(os.path.dirname(__file__), "..", "PhotoStyler", "Resources", "LUTs")

# --- helpers ---------------------------------------------------------------

def clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))

def lerp(a, b, t):
    return a + (b - a) * t

def s_curve(x, strength):
    """Contrast curve pinned at 0 and 1, so highlights/shadows never clip."""
    return clamp(x + strength * (x - 0.5) * (1.0 - abs(2.0 * x - 1.0)))

def luminance(r, g, b):
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

def lift_gamma_gain(c, lift, gain):
    return clamp(c * gain + lift * (1.0 - c))

# --- looks -----------------------------------------------------------------

def cinematic(r, g, b):
    """Teal shadows, warm highlights: the split-tone that reads as 'filmic'."""
    lum = luminance(r, g, b)
    r = lift_gamma_gain(r, -0.02, 1.04)
    g = lift_gamma_gain(g,  0.01, 1.00)
    b = lift_gamma_gain(b,  0.06, 0.97)
    # Weight the tint by tonal range so midtone skin stays believable.
    shadow_w = clamp((0.45 - lum) / 0.45)
    highlight_w = clamp((lum - 0.55) / 0.45)
    r = clamp(r + highlight_w * 0.055 - shadow_w * 0.020)
    g = clamp(g + highlight_w * 0.020 + shadow_w * 0.008)
    b = clamp(b - highlight_w * 0.045 + shadow_w * 0.060)
    return (s_curve(r, 0.18), s_curve(g, 0.18), s_curve(b, 0.18))

def warm_film(r, g, b):
    """Warm negative stock: lifted blacks, gentle roll-off, green-leaning mids."""
    r = clamp(r * 1.06 + 0.012)
    g = clamp(g * 1.01 + 0.016)
    b = clamp(b * 0.94 + 0.010)
    lum = luminance(r, g, b)
    mid_w = 1.0 - abs(2.0 * lum - 1.0)
    g = clamp(g + mid_w * 0.012)
    # Matte the blacks the way a print does.
    r, g, b = (lerp(c, c * 0.93 + 0.07, 0.55) for c in (r, g, b))
    return (s_curve(r, 0.10), s_curve(g, 0.10), s_curve(b, 0.08))

def airy(r, g, b):
    """Bright and open: lifted exposure, softened contrast, cool-clean whites."""
    r, g, b = (clamp(c * 1.05 + 0.03) for c in (r, g, b))
    lum = luminance(r, g, b)
    highlight_w = clamp((lum - 0.6) / 0.4)
    b = clamp(b + highlight_w * 0.02)
    return (s_curve(r, -0.10), s_curve(g, -0.10), s_curve(b, -0.09))

def monochrome(r, g, b):
    """Panchromatic black and white with a deep, contrasty print curve."""
    # Red-weighted mix keeps skin bright and separates it from foliage.
    y = clamp(0.30 * r + 0.59 * g + 0.11 * b)
    y = s_curve(y, 0.30)
    y = clamp(y * 0.98 + 0.012)
    return (y, y, y)

LOOKS = {
    "Cinematic":  ("PhotoStyler Cinematic",  cinematic),
    "WarmFilm":   ("PhotoStyler Warm Film",  warm_film),
    "Airy":       ("PhotoStyler Airy",       airy),
    "Monochrome": ("PhotoStyler Monochrome", monochrome),
}

# --- writer ----------------------------------------------------------------

def write_cube(name, title, fn):
    path = os.path.join(OUT, name + ".cube")
    with open(path, "w") as f:
        f.write("# Generated by tools/generate_luts.py\n")
        f.write("# Placeholder starter look - replace with an exported Lightroom LUT.\n")
        f.write('TITLE "%s"\n' % title)
        f.write("LUT_3D_SIZE %d\n" % SIZE)
        f.write("DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write("DOMAIN_MAX 1.0 1.0 1.0\n")
        # Red varies fastest, then green, then blue - the order CIColorCube wants.
        for bi in range(SIZE):
            for gi in range(SIZE):
                for ri in range(SIZE):
                    r, g, b = fn(ri / (SIZE - 1), gi / (SIZE - 1), bi / (SIZE - 1))
                    f.write("%.6f %.6f %.6f\n" % (r, g, b))
    return path, os.path.getsize(path)

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for name, (title, fn) in LOOKS.items():
        path, size = write_cube(name, title, fn)
        print("%-12s %7.1f KB  %s" % (name, size / 1024.0, os.path.basename(path)))
